set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'gregsexton/gitv'
Plugin 'Townk/vim-autoclose'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-surround'
Plugin 'tomtom/tcomment_vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'vim-ruby/vim-ruby'
Plugin 'vim-scripts/taglist.vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'sunaku/vim-ruby-minitest'
Plugin 'sjl/gundo.vim'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'airblade/vim-gitgutter'
Plugin 'skalnik/vim-vroom'
Plugin 'groenewege/vim-less'
Plugin 'jpalardy/vim-slime'
Plugin 'rking/ag.vim'
Plugin 'xolox/vim-misc'
call vundle#end()

runtime macros/matchit.vim
filetype plugin indent off

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" BASIC EDITING CONFIGURATION
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set si
set shell=/bin/sh
set clipboard=unnamed
set novisualbell
set autoread
set hidden
set nowrap
set winwidth=80
set colorcolumn=81
set history=10000
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set laststatus=2
set showmatch
set incsearch
set hlsearch
set relativenumber
set number
set nobackup
set nowb
set noswapfile
set linebreak
set ignorecase smartcase
set cursorline
set magic
set cursorcolumn
set cmdheight=2
set switchbuf=useopen
set numberwidth=4
set showtabline=2
" Prevent Vim from clobbering the scrollback buffer. See
" http://www.shallowsky.com/linux/noaltscreen.html
set t_ti= t_te=
set scrolloff=3
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
" display incomplete commands
set showcmd
" Enable highlighting for syntax
syntax on
" Enable file type detection.
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
" Also load indent files, to automatically do language-dependent indenting.
filetype plugin indent on
" use emacs-style tab completion when selecting files, etc
set wildmode=longest,list
" make tab completion for files/buffers act like bash
set wildmenu
let mapleader=","

" remap the semicolon to be colon
nnoremap ; :

map <leader>ba :1,300 bd!<br>

" Fast saving in all modes
nnoremap <Leader>w :w<CR>
inoremap <C-w> <Esc>:w<CR>
vnoremap <Leader>w <Esc>:w<CR>

" Write the file when leavin insert mode
:au InsertLeave <buffer> w

map <leader>f :CtrlP<cr>
let g:ctrlp_working_path_mode = 'ra'
" Make CtrlP use ag for listing the files. Way faster and no useless files.
" This ignores hidden files
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
let g:ctrlp_use_caching = 0
" Enable MRU for CtrlP
let g:ctrlp_cmd = 'CtrlP'


autocmd! bufwritepost .vimrc source ~/.vimrc

augroup vimrcEx
  " Clear all autocmds in the group
  autocmd!
  autocmd FileType text setlocal textwidth=78
  " Jump to last cursor position unless it's invalid or in an event handler
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  "for ruby, autoindent with two spaces, always expand tabs
  autocmd FileType ruby,haml,eruby,yaml,html,javascript,sass,cucumber set ai sw=2 sts=2 et
  autocmd FileType python set sw=4 sts=4 et

  autocmd! BufRead,BufNewFile *.sass setfiletype sass

  autocmd BufRead *.mkd  set ai formatoptions=tcroqn2 comments=n:&gt;
  autocmd BufRead *.markdown  set ai formatoptions=tcroqn2 comments=n:&gt;
  " Don't syntax highlight markdown because it's often wrong
  autocmd! FileType mkd setlocal syn=off
  autocmd! FileType markdown setlocal syn=off

  " Leave the return key alone when in command line windows, since it's used
  " to run commands there.
  autocmd! CmdwinEnter * :unmap <cr>
  autocmd! CmdwinLeave * :call MapCR()
augroup END

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" COLOR
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
:set t_Co=256 " 256 colors
:set background=dark
:color railscasts

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" MISC KEY MAPS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Move around splits with <c-hjkl>
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" use either key combo to leave mode
inoremap kj <esc>
inoremap jk <esc>

" Clear the search buffer when hitting return
function! MapCR()
  nnoremap <space> :nohlsearch<cr>
endfunction
call MapCR()

" OPEN FILES IN DIRECTORY OF CURRENT FILE
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%
map <leader>v :view %%

" Strip whitespace on buffer write using the better-whitespace plugin
autocmd BufWritePre * StripWhitespace

let g:LustyExplorerSuppressRubyWarning = 1

" In insert mode, cursor is a pipe. In normal mode, a block
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

:hi ColorColumn guibg=#2d2d2d ctermbg=229 ctermfg=236
:hi CursorColumn guibg=#2d2d2d ctermbg=234

" using vroom to run tests, do not clear the screen before the run
let g:vroom_clear_screen=0

" This is used to remove accents from the YouTube adjustment reports so they
" process through the SIP system correctly.
:map <F3> :%s/.*/\=tr(submatch(0), 'óèâìÎ·²ïæçùãÿøþò¿ü¨êÜë´öäáàôåíúéàñÑÏÉÍÀÈÁÞØ','oeaii__iacuayopo_u_eUe_oaaaoaiueanNIE__IAEA_O_')

" Map up and down arrow keys to move lines and visual selections in
" normal, insert and visual modes
nnoremap <Up> :m .-2<CR>==
nnoremap <Down> :m .+1<CR>==
inoremap <Up> <Esc>:m .-2<CR>==gi
inoremap <Down> <Esc>:m .+1<CR>==gi
vnoremap <Up> :m '<-2<CR>gv=gv''
vnoremap <Down> :m '>+1<CR>gv=gv
" Move characters left/right using the arrow keys
nnoremap <Right> xp
nnoremap <Left> Xph

" with out this, editing crontabs fails on some machines
autocmd filetype crontab setlocal nobackup nowritebackup

" Map whole line completion to a single key
inoremap <C-l> <C-x><C-l>

