# ~/.tmuxinator/project.yml
# you can make as many tabs as you wish...

project_name: projects 
project_root: ~/projects
socket_name: foo # Not needed.  Remove to use default socket
rvm: 1.9.3
tabs:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - #empty, will just run plain bash
  - console:
